const prompts = [
    "Share a piece of dating lore about yourself.",
    "What’s your most unbelievable coincidence?",
    "Tell a story about a time you got completely lost.",
    "Describe a small decision that changed everything.",
    "Share a piece of embarrassing lore from your childhood.",
    "Tell a story about the strangest food you’ve ever eaten.",
    "Describe a moment when you accidentally scared someone.",
    "Share a time you got caught in an awkward lie.",
    "Tell a story about a time you were completely out of your comfort zone.",
    "Describe the weirdest encounter you’ve ever had with a stranger.",
    "Descrive a rumor about you that’s totally untrue.",
    "Share a time you witnessed something unexplainable.",
    "Tell a story about the most ridiculous thing you believed as a kid.",
    "Describe a moment when luck was ridiculously on your side.",
    "What’s a piece of advice you followed that went horribly wrong?",
    "Describe a funny misunderstanding you’ve been part of.",
    "Share a time you got caught in an awkward lie.",
    "Tell a story about the most ridiculous thing you believed as a kid.",
    "Share a moment you accidentally became the hero of a story.",
    "What’s the most awkward social encounter you’ve ever had?",
    "Tell a story about a prank you’ve pulled or been a victim of.",
    "Describe a time you found yourself in a totally unexpected place.",
    "What’s the weirdest thing you’ve witnessed in public?",
    "Tell a story about a time you tried something you were scared of.",
    "Share a time you misunderstood a situation in a hilarious way.",
    "Tell a story about a coincidence that felt like fate.",
    "Describe a time you had to improvise in a totally absurd way.",
    "Share a story about a time you felt like you were in a movie.",
    "Describe the weirdest dream you’ve ever had that you remember.",
    "Tell a story about something you found in an unexpected place.",
    "Share a time you accidentally embarrassed someone else.",
    "Tell a story about a time you took a risk that actually worked.",
    "Share a moment you realized you were completely wrong about something.",
    "Share a story about a time you accidentally got into trouble.",
    "What’s a time you accidentally got involved in someone else’s drama?",
    "Share a time you got caught doing something ridiculous.",
    "Tell about the time you've been the most introspective.",
    "Share a moment when you were completely unprepared for a situation.",
    "What's the coolest thing you've done?",
    "Describe a time you accidentally embarrassed yourself in public.",
    "Share a story about a time you got caught sneaking or hiding.",
    "Tell a story about a time you accidentally broke a rule but got away with it.",
    "Share a story about a moment that felt like a plot twist in real life.",
    "What’s the silliest thing you’ve done to impress someone?",
    "Share a story about a time you found yourself in a surreal situation.",
    "Share the most wild adventure you've been on.",
    "Tell about a life or death situation.",
    "Share a story about a challenge you never thought you could overcome.",
    "Share a story of betrayal or unexpected deception.",
    "Tell a story about the time everything went wrong.",
    "Tell a story about a surprising friendship.",
    "Describe the most chaotic day of your life.",
    "Share a moment that changed the way you see the world.",
    "Tell a story about a time you acted impulsively and it worked out.",
    "Tell about a moment that felt like pure luck or fate.",
    "Describe a situation that spiraled completely out of control.",
    "Tell about the strangest rumor you’ve ever heard about yourself.",
    "Describe a time you narrowly escaped disaster in a strange way."
];
