const props = [
  "Rubber duck",
  "Rooftop",
  "Casserole",
  "Forklift",
  "3 a.m.",
  "Mysterious stranger",
  "Sock puppet",
  "Elevator music",
  "Half-eaten sandwich",
  "Sombrero",
  "Luggage",
  "Glow stick",
  "Pigeon",
  "Awkward handshake",
  "Broken mic",
  "Leftover pizza",
  "Door",
  "Hairbrush",
  "Old flip phone",
  "Traffic cone",
  "Banana peel",
  "Book",
  "Vacuum",
  "Oversized sunglasses",
  "Forgotten password",
  "Plastic flamingo",
  "Cactus",
  "Cat",
  "Expired coupon",
  "Bubble wrap",
  "Pillow",
  "Beeping pager",
  "Lost earring",
  "Spilled drink",
  "Flying stapler",
  "Swing",
  "Monster",
  "Ghost",
  "Random text message",
  "Lonely",
  "Melted ice cream",
  "Spaghetti",
  "Table",
  "Mailbox",
  "Misplaced keys",
  "Odd wallpaper",
  "Tangled headphone cord",
  "Weird shadow",
  "Running faucet",
  "Missing shoe",
  "Expired milk",
  "Broom",
  "Figurine",
  "Weird smell",
  "Random echo",
  "Leftovers",
  "Umbrella",
  "Falling leaf",
  "Soggy cereal",
  "Mysterious voicemail",
  "Shiny rock",
  "Wobbly chair",
  "Squeaky shoe",
  "Melting candle",
  "Flying item",
  "Stray balloon",
  "Broken remote",
  "Weird ringtone",
  "Laughing",
  "Bicycle",
  "Car",
  "Spilled paint",
  "Sneezing",
  "Dancing",
  "Mysterious",
  "Broken",
  "Disappearing",
  "Falling",
  "Floating",
  "Singing",
  "Bouncing",
  "Dizzy",
  "Hiccup",
  "Heart",
  "Warehouse",
  "Lounge",
  "Airport",
  "Fair",
  "Concert",
  "Mall",
  "Unhinged",
  "Crazy",

  "Backyard",
  "Train station",
  "Library",
  "Carnival",
  "Basement",
  "Rooftop",
  "Cemetery",
  "Festival",
  "Market",
  "Studio",
  "Garage",
  "Beach",
  "Nightclub",
  "Arcade",
  "Abandoned house",
  "Playground",
  "Church",
  "Hospital",
  "City park",
  "Subway",
  "Diner",
  "Theater",
  "Bridge",
  "Hotel",
  "Street corner",
  "Alley",
  "Lobby",
  "Penthouse",
  "Garden",
  "Museum",
  "Train car",
  "Forest",
  "Countryside",
  "Swamp",
  "Island",
  "Mountain",
  "Riverbank",
  "Desert",
  "Haunted house",
  "Dungeon",
  "Labyrinth",
  "Tower",
  "School",
  "Rave",
  "Boardwalk",
  "Boat",
  "Suburban street",
  "Skate park",
  "Ice rink",
  "Zoo",
  "Studio apartment",
  "Coffee shop",
  "Food court",
  "Gas station",
  "Parking lot",
  "Attic",
  "Porch",
  "Balcony",
  "Basement bar",
  "Night market",
  "Open field",
  "Street festival",
  "Train yard",
  "Parking garage",
  "Warehouse loft",
  "Factory floor",
  "Abandoned mall",
  "VIP section",
  "Backstage",
  "Loading dock",
  "Elevator",
  "Escalator",
  "Stairwell",
  "Fountain",
  "Bus stop",
  "Subway tunnel",
  "Train tracks",
  "Bridge overpass",
  "City square",
  "Crosswalk",
  "Traffic circle",
  "Roundabout",
  "Work"
];
